name: whatsaver
description: A flutter app to save WhatsApp statuses to storage on Android
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  path_provider: ^2.0.10
  permission_handler: ^9.2.0
  whatsapp_status_api:
    path: /home/amansikarwar/Development/projects/whatsaver/packages/whatsapp_status_api

dev_dependencies:
  bloc_test: ^9.0.3
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
